language: go

sudo: false

go:
    - 1.7.x
    - 1.8.x
    - tip

before_install:
    - mkdir -p $HOME/bin
    - curl -sL http://get.binhq.io/githubin | DEST=$HOME/bin bash
    - githubin get Masterminds/glide 0.12.3 -o $HOME/bin
    - make envcheck

install: make setup

script: make check

after_success: >
    if [[ "$TRAVIS_TAG" && $TRAVIS_GO_VERSION =~ ^1\.8(\.[0-9]+)?$ ]]; then
        githubin get goreleaser/goreleaser 0.8.9 -o $HOME/bin
        goreleaser
    fi
