dist: trusty
sudo: required

language: go

go:
    - 1.7.x
    - 1.8.x
    - tip

before_install:
    - mkdir -p $HOME/bin
    - curl -sL http://get.binhq.io/gitbin | DEST=$HOME/bin bash
    - gitbin get golang/dep 0.3.0 -o $HOME/bin
    - make envcheck

install: make setup

script: make check

after_success: >
    if [[ "$TRAVIS_TAG" && $TRAVIS_GO_VERSION =~ ^1\.8(\.[0-9]+)?$ ]]; then
        gitbin get goreleaser/goreleaser 0.28.3 -o $HOME/bin
        sudo apt-get update
        sudo apt-get install --yes snapd
        export PATH=/snap/bin:$PATH
        sudo snap install snapcraft --candidate --classic
        goreleaser
    fi
