// Code generated by protoc-gen-go.
// source: githubin/v1alpha1/githubin.proto
// DO NOT EDIT!

/*
Package githubin is a generated protocol buffer package.

It is generated from these files:
	githubin/v1alpha1/githubin.proto

It has these top-level messages:
	BinarySearch
	BinaryDownload
*/
package githubin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BinaryDownload_DownloadType int32

const (
	BinaryDownload_BINARY BinaryDownload_DownloadType = 0
	BinaryDownload_GZIP   BinaryDownload_DownloadType = 1
	BinaryDownload_ZIP    BinaryDownload_DownloadType = 2
)

var BinaryDownload_DownloadType_name = map[int32]string{
	0: "BINARY",
	1: "GZIP",
	2: "ZIP",
}
var BinaryDownload_DownloadType_value = map[string]int32{
	"BINARY": 0,
	"GZIP":   1,
	"ZIP":    2,
}

func (x BinaryDownload_DownloadType) String() string {
	return proto.EnumName(BinaryDownload_DownloadType_name, int32(x))
}
func (BinaryDownload_DownloadType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type BinarySearch struct {
	Owner      string `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	Repository string `protobuf:"bytes,2,opt,name=repository" json:"repository,omitempty"`
	Version    string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Os         string `protobuf:"bytes,4,opt,name=os" json:"os,omitempty"`
	Arch       string `protobuf:"bytes,5,opt,name=arch" json:"arch,omitempty"`
}

func (m *BinarySearch) Reset()                    { *m = BinarySearch{} }
func (m *BinarySearch) String() string            { return proto.CompactTextString(m) }
func (*BinarySearch) ProtoMessage()               {}
func (*BinarySearch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BinarySearch) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *BinarySearch) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *BinarySearch) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *BinarySearch) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *BinarySearch) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type BinaryDownload struct {
	Url  string                      `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Type BinaryDownload_DownloadType `protobuf:"varint,2,opt,name=type,enum=binhq.githubin.v1alpha1.BinaryDownload_DownloadType" json:"type,omitempty"`
	Path string                      `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
}

func (m *BinaryDownload) Reset()                    { *m = BinaryDownload{} }
func (m *BinaryDownload) String() string            { return proto.CompactTextString(m) }
func (*BinaryDownload) ProtoMessage()               {}
func (*BinaryDownload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BinaryDownload) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *BinaryDownload) GetType() BinaryDownload_DownloadType {
	if m != nil {
		return m.Type
	}
	return BinaryDownload_BINARY
}

func (m *BinaryDownload) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*BinarySearch)(nil), "binhq.githubin.v1alpha1.BinarySearch")
	proto.RegisterType((*BinaryDownload)(nil), "binhq.githubin.v1alpha1.BinaryDownload")
	proto.RegisterEnum("binhq.githubin.v1alpha1.BinaryDownload_DownloadType", BinaryDownload_DownloadType_name, BinaryDownload_DownloadType_value)
}

func init() { proto.RegisterFile("githubin/v1alpha1/githubin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x1f, 0x6d, 0xe3, 0x50, 0x42, 0x18, 0x04, 0x17, 0x0f, 0x52, 0x02, 0xa2, 0x17, 0x53,
	0x5a, 0xfd, 0x03, 0x06, 0xa1, 0xf6, 0x22, 0x12, 0xbd, 0xd8, 0x93, 0x1b, 0x5d, 0xcc, 0x42, 0xd8,
	0x5d, 0x37, 0x69, 0x4b, 0xae, 0xfe, 0x21, 0xff, 0xa2, 0x64, 0x93, 0x95, 0x7a, 0x10, 0x7b, 0x7b,
	0xf3, 0xe6, 0xed, 0xbc, 0x37, 0x3b, 0x30, 0x79, 0xe7, 0x75, 0xb1, 0xce, 0xb9, 0x98, 0x6e, 0x66,
	0xb4, 0x54, 0x05, 0x9d, 0x4d, 0x2d, 0x93, 0x28, 0x2d, 0x6b, 0x89, 0xc7, 0x39, 0x17, 0xc5, 0x47,
	0xf2, 0xc3, 0x5a, 0x5d, 0xfc, 0xe9, 0xc0, 0x38, 0xe5, 0x82, 0xea, 0xe6, 0x91, 0x51, 0xfd, 0x5a,
	0xe0, 0x11, 0x0c, 0xe4, 0x56, 0x30, 0x4d, 0x9c, 0x89, 0x73, 0x71, 0x98, 0x75, 0x05, 0x9e, 0x02,
	0x68, 0xa6, 0x64, 0xc5, 0x6b, 0xa9, 0x1b, 0xe2, 0x9a, 0xd6, 0x0e, 0x83, 0x04, 0x46, 0x1b, 0xa6,
	0x2b, 0x2e, 0x05, 0xf1, 0x4c, 0xd3, 0x96, 0x18, 0x82, 0x2b, 0x2b, 0xe2, 0x1b, 0xd2, 0x95, 0x15,
	0x22, 0xf8, 0xad, 0x0f, 0x19, 0x18, 0xc6, 0xe0, 0xf8, 0xcb, 0x81, 0xb0, 0x0b, 0x71, 0x2b, 0xb7,
	0xa2, 0x94, 0xf4, 0x0d, 0x23, 0xf0, 0xd6, 0xba, 0xec, 0x43, 0xb4, 0x10, 0xef, 0xc0, 0xaf, 0x1b,
	0xc5, 0x8c, 0x79, 0x38, 0xbf, 0x4e, 0xfe, 0xd8, 0x28, 0xf9, 0x3d, 0x28, 0xb1, 0xe0, 0xa9, 0x51,
	0x2c, 0x33, 0x13, 0xda, 0x08, 0x8a, 0xd6, 0x45, 0x9f, 0xd4, 0xe0, 0xf8, 0x12, 0xc6, 0xbb, 0x4a,
	0x04, 0x18, 0xa6, 0xcb, 0xfb, 0x9b, 0xec, 0x39, 0x3a, 0xc0, 0x00, 0xfc, 0xc5, 0x6a, 0xf9, 0x10,
	0x39, 0x38, 0x02, 0xaf, 0x05, 0xee, 0xbc, 0x84, 0x60, 0xd1, 0x3b, 0xe3, 0x0b, 0x84, 0xf6, 0x69,
	0xe7, 0x8d, 0x67, 0xff, 0x84, 0xeb, 0xbe, 0xfa, 0xe4, 0x7c, 0xcf, 0x1d, 0x52, 0x58, 0x05, 0x56,
	0x93, 0x0f, 0xcd, 0x41, 0xaf, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x44, 0xe2, 0x3b, 0xf4,
	0x01, 0x00, 0x00,
}
