// Code generated by protoc-gen-go.
// source: githubin/v1alpha1/githubin.proto
// DO NOT EDIT!

/*
Package githubin is a generated protocol buffer package.

It is generated from these files:
	githubin/v1alpha1/githubin.proto

It has these top-level messages:
	BinarySearch
	BinaryDownload
*/
package githubin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BinaryDownload_Format int32

const (
	BinaryDownload_BINARY BinaryDownload_Format = 0
	BinaryDownload_TARGZ  BinaryDownload_Format = 1
	BinaryDownload_ZIP    BinaryDownload_Format = 2
)

var BinaryDownload_Format_name = map[int32]string{
	0: "BINARY",
	1: "TARGZ",
	2: "ZIP",
}
var BinaryDownload_Format_value = map[string]int32{
	"BINARY": 0,
	"TARGZ":  1,
	"ZIP":    2,
}

func (x BinaryDownload_Format) String() string {
	return proto.EnumName(BinaryDownload_Format_name, int32(x))
}
func (BinaryDownload_Format) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// Search criteria for a binary download
// First two are mandatory
// If version is empty, aim for the latest
// When os or arch is empty, it probably does not matter
type BinarySearch struct {
	Owner      string `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	Repository string `protobuf:"bytes,2,opt,name=repository" json:"repository,omitempty"`
	Version    string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Os         string `protobuf:"bytes,4,opt,name=os" json:"os,omitempty"`
	Arch       string `protobuf:"bytes,5,opt,name=arch" json:"arch,omitempty"`
}

func (m *BinarySearch) Reset()                    { *m = BinarySearch{} }
func (m *BinarySearch) String() string            { return proto.CompactTextString(m) }
func (*BinarySearch) ProtoMessage()               {}
func (*BinarySearch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BinarySearch) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *BinarySearch) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *BinarySearch) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *BinarySearch) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *BinarySearch) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

// Binary download information
type BinaryDownload struct {
	Url    string                `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Format BinaryDownload_Format `protobuf:"varint,2,opt,name=format,enum=binhq.githubin.v1alpha1.BinaryDownload_Format" json:"format,omitempty"`
	Path   string                `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
}

func (m *BinaryDownload) Reset()                    { *m = BinaryDownload{} }
func (m *BinaryDownload) String() string            { return proto.CompactTextString(m) }
func (*BinaryDownload) ProtoMessage()               {}
func (*BinaryDownload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BinaryDownload) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *BinaryDownload) GetFormat() BinaryDownload_Format {
	if m != nil {
		return m.Format
	}
	return BinaryDownload_BINARY
}

func (m *BinaryDownload) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*BinarySearch)(nil), "binhq.githubin.v1alpha1.BinarySearch")
	proto.RegisterType((*BinaryDownload)(nil), "binhq.githubin.v1alpha1.BinaryDownload")
	proto.RegisterEnum("binhq.githubin.v1alpha1.BinaryDownload_Format", BinaryDownload_Format_name, BinaryDownload_Format_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Githubin service

type GithubinClient interface {
	// Look for binary download information
	FindBinary(ctx context.Context, in *BinarySearch, opts ...grpc.CallOption) (*BinaryDownload, error)
}

type githubinClient struct {
	cc *grpc.ClientConn
}

func NewGithubinClient(cc *grpc.ClientConn) GithubinClient {
	return &githubinClient{cc}
}

func (c *githubinClient) FindBinary(ctx context.Context, in *BinarySearch, opts ...grpc.CallOption) (*BinaryDownload, error) {
	out := new(BinaryDownload)
	err := grpc.Invoke(ctx, "/binhq.githubin.v1alpha1.Githubin/FindBinary", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Githubin service

type GithubinServer interface {
	// Look for binary download information
	FindBinary(context.Context, *BinarySearch) (*BinaryDownload, error)
}

func RegisterGithubinServer(s *grpc.Server, srv GithubinServer) {
	s.RegisterService(&_Githubin_serviceDesc, srv)
}

func _Githubin_FindBinary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinarySearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubinServer).FindBinary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/binhq.githubin.v1alpha1.Githubin/FindBinary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubinServer).FindBinary(ctx, req.(*BinarySearch))
	}
	return interceptor(ctx, in, info, handler)
}

var _Githubin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "binhq.githubin.v1alpha1.Githubin",
	HandlerType: (*GithubinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindBinary",
			Handler:    _Githubin_FindBinary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "githubin/v1alpha1/githubin.proto",
}

func init() { proto.RegisterFile("githubin/v1alpha1/githubin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x6d, 0xbb, 0x76, 0xdb, 0x43, 0x4a, 0x79, 0x08, 0x06, 0x0f, 0x32, 0x0a, 0xe2, 0x4e,
	0x19, 0x9b, 0x9f, 0x60, 0x45, 0x3a, 0x76, 0x11, 0xa9, 0x5e, 0x2c, 0x5e, 0x52, 0x57, 0x4d, 0xa0,
	0x26, 0x35, 0xed, 0x36, 0x76, 0xf5, 0xd3, 0xf8, 0x31, 0xa5, 0x69, 0x2b, 0x7a, 0x10, 0xbd, 0xbd,
	0xf7, 0x7f, 0xff, 0x97, 0xff, 0x2f, 0x09, 0x4c, 0x5e, 0x44, 0xcd, 0xb7, 0x99, 0x90, 0xb3, 0xdd,
	0x9c, 0x15, 0x25, 0x67, 0xf3, 0x59, 0xaf, 0xd0, 0x52, 0xab, 0x5a, 0xe1, 0x69, 0x26, 0x24, 0x7f,
	0xa3, 0x5f, 0x6a, 0xef, 0x0b, 0xdf, 0x2d, 0x38, 0x8e, 0x84, 0x64, 0xfa, 0x70, 0x97, 0x33, 0xfd,
	0xc4, 0xf1, 0x04, 0x5c, 0xb5, 0x97, 0xb9, 0x26, 0xd6, 0xc4, 0x9a, 0x8e, 0x93, 0xb6, 0xc1, 0x73,
	0x00, 0x9d, 0x97, 0xaa, 0x12, 0xb5, 0xd2, 0x07, 0x62, 0x9b, 0xd1, 0x37, 0x05, 0x09, 0x0c, 0x77,
	0xb9, 0xae, 0x84, 0x92, 0xc4, 0x31, 0xc3, 0xbe, 0x45, 0x1f, 0x6c, 0x55, 0x91, 0x81, 0x11, 0x6d,
	0x55, 0x21, 0xc2, 0xa0, 0xc9, 0x21, 0xae, 0x51, 0x4c, 0x1d, 0x7e, 0x58, 0xe0, 0xb7, 0x10, 0xd7,
	0x6a, 0x2f, 0x0b, 0xc5, 0x36, 0x18, 0x80, 0xb3, 0xd5, 0x45, 0x07, 0xd1, 0x94, 0x18, 0x83, 0xf7,
	0xac, 0xf4, 0x2b, 0xab, 0x4d, 0xbc, 0xbf, 0xa0, 0xf4, 0x97, 0x3b, 0xd1, 0x9f, 0x47, 0xd1, 0xd8,
	0x6c, 0x25, 0xdd, 0x76, 0x03, 0x50, 0xb2, 0x9a, 0x77, 0x9c, 0xa6, 0x0e, 0xa7, 0xe0, 0xb5, 0x2e,
	0x04, 0xf0, 0xa2, 0xf5, 0xcd, 0x32, 0x79, 0x08, 0x8e, 0x70, 0x0c, 0xee, 0xfd, 0x32, 0x59, 0xa5,
	0x81, 0x85, 0x43, 0x70, 0xd2, 0xf5, 0x6d, 0x60, 0x2f, 0x38, 0x8c, 0x56, 0x5d, 0x20, 0x3e, 0x02,
	0xc4, 0x42, 0x6e, 0xda, 0x38, 0xbc, 0xf8, 0x83, 0xa7, 0x7d, 0xdf, 0xb3, 0xcb, 0x7f, 0x62, 0x47,
	0x90, 0x8e, 0x7a, 0x4f, 0xe6, 0x99, 0x5f, 0xbc, 0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xe6,
	0xe0, 0x4c, 0xe9, 0x01, 0x00, 0x00,
}
